### ISSUE TITLE
product icons

### ISSUE THREAD

**Issue by mecs13** [mecs13/website_text#10]
+- click "products" 
+- landed on products homepage
+- image for "architecture" and 'infinite" are the same

kyles comp/os

**Comment by tbinetruy** [comment]
@mecs13 , not a 'bug' per se, it's the expected behavior from the code. I just got the same image from both. So classifying it as 'enhancement'. Technically it's the same thing from blog articles that all have NYE's icon.

@kylekesses , please get needed icons from Jacques.
