### ISSUE TITLE
Design Intro text

### ISSUE THREAD

**Issue by kylekesses** [mecs13/website_text#126]
Text should read...

In XR, the term "Design" has two identities. First, we work together with you to design the XR world you wish to build. Next, we design 3D models of your vision to be implemented by the development team.
...

Talked today with thomas about how the graphics engine (which communicates 3D features to a 2D machine) works with the physics engine (which allows the computer/code to interpret physical world object behaviors such as reactions to gravity).

**Comment by mecs13** [comment]
nice.  Calendar it in for your April please.
