### ISSUE TITLE
Partnership --> Careers --> Designer 

### ISSUE THREAD

**Issue by kylekesses** [mecs13/website_text#149]
Review with JB what we are looking for in Designers

Learned from interview with Kacy.

April Launch Draft 1 below

@mecs13 please review for accuracy 
...

Syncing designers and developers is at the core of XR creation. Blending 3D models with C-based programming languages makes VR tick. 

Designers working in Blender are the artist crafting Virtual graphics. Artist with spacial design interest combined with fluency in Adobe programs (illustrator, photoshop, premier, in design) have the creative foundation necessary for successful 3D design.

**Comment by mecs13** [comment]
delte "c-base"
delete "blender" and put "graphics engine"
delete "Adobe" and put "design suites", to illustrate, photo edit, publishing layout,
