### ISSUE TITLE
Consultation Intro

### ISSUE THREAD

**Issue by kylekesses** [mecs13/website_text#160]
Please upload the below as the revised text under Consultation intro 
...

Virtual Reality (VR) and Augmented Reality (AR), fitting under the parent term "Extended Reality", enhance communication, collaboration, and education. Unlike it's predecessors, XR Media is interactive, calling on the user to embody her consciousness.

These technologies will increasingly be in the home, integrating with daily living in the way televisions, computers, and phones already have. As of today, you can engage with simulated environments through your phone (or XR glasses/goggles).

Historical rates of technological adoption suggest 25% of the US population will have an AR/VR in their homes within the next five years. It's the next frontier of human connectivity.

In business, XR Media cuts internal costs by providing immersive training programs and business travel alternatives. When used to drive revenue, XR is a natural marketing tool, the backdrop for new age content creation.  

XR Media can be the ultimate communication tool or the reason your business falls behind.

**Comment by mecs13** [comment]
Do we have the growth chart to include here?  This is a very powerful chart Jacques formated in his first weeks here.  let's please include it.   @JacquesLalo where is this, proposal assets?
