### ISSUE TITLE
biz prop allignment

### ISSUE THREAD

**Issue by mecs13** [mecs13/website_text#185]
build prop from admin panel
check link
open content
allignment issues.

![image](https://user-images.githubusercontent.com/25008118/41928344-e184da50-7942-11e8-87a2-2165e47ed878.png)

chrome, windows

**Comment by tbinetruy** [comment]
It might come from a few things... Can you please answer the following questions ?

Does it do it for all the business props ? Does it do it on your mac ? What about on Firefox ?

Thanks !

**Comment by mecs13** [comment]
it was doing it for multiple, not sure if all.  no problem on my mac.
cannot open firefox atm
