### ISSUE TITLE
pr text

### ISSUE THREAD

**Issue by mecs13** [mecs13/website_text#190]
re-write this from the perspective Kristen is going to read this.  I think you might express us differently.  maybe not though.   lmk!! we talk about it 

https://www.dropbox.com/s/xdy559vdrbvsnef/Screenshot%202018-06-28%2023.40.18.png?dl=0

**Comment by kylekesses** [comment]
Yea I think this one came out of my negative perception of PR. To me, PR is the manipulation of the truth to make the client seem less guilty or more praiseworthy than they are. We'll chat about it at Saturday's one on one and come up with a solution. Remind me who Kristen is...
