### ISSUE TITLE
homepage design

### ISSUE THREAD

**Issue by mecs13** [mecs13/website_text#198]
"-I think you should just have your name with the logo right straight front and center - " - female NYC 30s
" - Whats the name of your company??"  - male 40s, nyc

" too much info on the front page" - female, 20s, nyc

**Comment by tbinetruy** [comment]
too much info on the front page ??

**Comment by mecs13** [comment]
Yes, we need to reduce this to a single message and a single action (maybe 2 possible actions)

As in.  let's remove the XR definition and look at a new homepage design.  The feedback is strongly expressing that it is not clean/simple/easy to digest
