### ISSUE TITLE
client portal dashboard

### ISSUE THREAD

**Issue by mecs13** [mecs13/website_text#46]
- go to client portal page
- told it is coming soon
- should have a dashboard that appears accessible beyond login

**Comment by mecs13** [comment]
Dashboard to include:
Tabs such as: client name, date, campaign, metrics, strategy, contact
broken into suctions such asL
- graphs
- tables
- data logs
- text

**Comment by tbinetruy** [comment]
Need graphics. See with @JacquesLalo , potentially a substantial amount of work.
