### ISSUE TITLE
Menu Issues

### ISSUE THREAD

**Issue by myarmolinsky** [mecs13/website_text#5]
1. I tried this multiple times to make sure this wasn't a one-time thing: Click on something from the menu on the left like Partnership (click Partnership itself, not its sub categories)
2. The category stays open but when you hover with your mouse to click a subcategory, the menu closes as if you were simply hovering over it with your mouse, and it doesn't  give you a chance to click on a subcategory
3. Clicking on a category shouldn't do anything, you should only be able to hover over it
4. Google Chrome
5. PC

**Comment by tbinetruy** [comment]
amazing bug reporting. Thanks ;)

on it

**Comment by tbinetruy** [comment]
fixed
