### ISSUE TITLE
white on white

### ISSUE THREAD

**Issue by mecs13** [mecs13/website_text#7]
go to legal page --> open menu
menu is white and legal page is white, and the lines/boxes/text over lap
i expected the menu to be layered over the background, and not translucent
mac 
firefox
and chrome

**Comment by tbinetruy** [comment]
awesome, thanks !

**Comment by tbinetruy** [comment]
I don't get the bug. Please send me a screen shot.


![7](https://user-images.githubusercontent.com/19936648/36280542-9ae918ea-1268-11e8-92fe-ec675cdb27d8.png)


actually, in mobile I had a different bug where the menu what black but the about us content didn't disapear on menu opening on mobile. i just fixed that though. Here's an eg of what it was like, was that your problem?

![7-2](https://user-images.githubusercontent.com/19936648/36280615-d7121eac-1268-11e8-9a9f-b23fc68fbb9e.png)
