### ISSUE TITLE
homepage misalign

### ISSUE THREAD

**Issue by mecs13** [mecs13/website_text#94]
In full screen chrome homepage is misaligned 
![image](https://user-images.githubusercontent.com/25008118/37685199-ee881a5e-2c68-11e8-84a4-f5ab39f82d0d.png)

![image](https://user-images.githubusercontent.com/25008118/37685177-dde19202-2c68-11e8-9fc6-d0f14545beb7.png)

**Comment by tbinetruy** [comment]
note to self: font-size proportional to page height for this para. need to mofidy this.
